/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// main.ts
var main_exports = {};
__export(main_exports, {
  default: () => BrainsryoPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian3 = require("obsidian");

// BrainsryoApi.ts
var import_obsidian = require("obsidian");
var BrainsryoApi = class {
  constructor(baseUrl, token) {
    this.baseUrl = baseUrl.replace(/\/$/, "");
    this.token = token;
  }
  getHeaders() {
    return {
      "Authorization": `Bearer ${this.token}`,
      "Content-Type": "application/json"
    };
  }
  async listMemos() {
    const url = `${this.baseUrl}/api/external/memos`;
    console.log(`\u{1F4E1} Requesting List: ${url}`);
    try {
      const response = await (0, import_obsidian.requestUrl)({
        url,
        method: "GET",
        headers: this.getHeaders()
      });
      return response.json;
    } catch (err) {
      console.error(`\u274C List Fetch Failed:`, err);
      throw err;
    }
  }
  async getMemo(uuid) {
    const url = `${this.baseUrl}/api/external/memos/${uuid}`;
    console.log(`\u{1F4E1} Requesting Detail: ${url}`);
    try {
      const response = await (0, import_obsidian.requestUrl)({
        url,
        method: "GET",
        headers: this.getHeaders()
      });
      return response.json;
    } catch (err) {
      console.error(`\u274C Detail Fetch Failed (${uuid}):`, err);
      throw err;
    }
  }
  async updateMemo(uuid, data) {
    const url = `${this.baseUrl}/api/external/memos/${uuid}`;
    try {
      const response = await (0, import_obsidian.requestUrl)({
        url,
        method: "POST",
        headers: this.getHeaders(),
        body: JSON.stringify(data)
      });
      return response.json;
    } catch (err) {
      console.error(`\u274C Update Failed:`, err);
      throw err;
    }
  }
  async deleteMemo(uuid) {
    const response = await (0, import_obsidian.requestUrl)({
      url: `${this.baseUrl}/api/external/memos/${uuid}`,
      method: "DELETE",
      headers: this.getHeaders()
    });
    return response.json;
  }
  async uploadFile(fileData, fileName) {
    const formData = new FormData();
    const blob = new Blob([fileData]);
    formData.append("file", blob, fileName);
    try {
      const response = await fetch(`${this.baseUrl}/api/external/upload`, {
        method: "POST",
        headers: {
          "Authorization": `Bearer ${this.token}`
        },
        body: formData
      });
      if (!response.ok) {
        const errorText = await response.text();
        throw new Error(`Upload failed: ${response.status} ${errorText}`);
      }
      return await response.json();
    } catch (e) {
      console.error("API Upload Error:", e);
      throw e;
    }
  }
};

// BridgeManager.ts
var import_obsidian2 = require("obsidian");
var BridgeManager = class {
  constructor(app, api, settings) {
    this.app = app;
    this.api = api;
    this.settings = settings;
  }
  async pushNote(file) {
    var _a, _b;
    const cache = this.app.metadataCache.getFileCache(file);
    const uuid = (_a = cache == null ? void 0 : cache.frontmatter) == null ? void 0 : _a.uuid;
    if (!uuid) {
      new import_obsidian2.Notice("\u274C \uC774 \uD30C\uC77C\uC740 UUID\uAC00 \uC5C6\uC5B4 \uC11C\uBC84\uB85C \uC804\uC1A1\uD560 \uC218 \uC5C6\uC2B5\uB2C8\uB2E4.");
      return;
    }
    const fmEnc = (_b = cache == null ? void 0 : cache.frontmatter) == null ? void 0 : _b.is_encrypted;
    const isEncrypted = fmEnc === 1 || fmEnc === true || fmEnc === "1";
    if (isEncrypted) {
      const confirm = window.confirm("\u{1F512} \uC774 \uBA54\uBAA8\uB294 \uC554\uD638\uD654\uB418\uC5B4 \uC788\uC2B5\uB2C8\uB2E4. \uC218\uC815\uB41C \uC554\uD638\uBB38\uC744 \uC11C\uBC84\uB85C \uBCF4\uB0B4\uC2DC\uACA0\uC2B5\uB2C8\uAE4C? (\uC798\uBABB\uB41C \uC218\uC815\uC740 \uB370\uC774\uD130 \uD30C\uAD34\uB85C \uC774\uC5B4\uC9C8 \uC218 \uC788\uC2B5\uB2C8\uB2E4)");
      if (!confirm)
        return;
    }
    try {
      let content = await this.app.vault.read(file);
      content = await this.processAttachments(content, file.path);
      await this.api.updateMemo(uuid, {
        content,
        title: file.basename
      });
      new import_obsidian2.Notice(`\u{1F680} \uC11C\uBC84\uB85C \uC804\uC1A1 \uC644\uB8CC: ${file.basename}`);
    } catch (e) {
      console.error("Push Error:", e);
      new import_obsidian2.Notice(`\u274C \uC804\uC1A1 \uC2E4\uD328: ${e.message}`);
    }
  }
  async processAttachments(content, sourcePath) {
    const wikiLinkRegex = /!\[\[(.*?)\]\]|\[\[(.*?)\]\]/g;
    let match;
    let newContent = content;
    const matches = Array.from(content.matchAll(wikiLinkRegex));
    for (const match2 of matches) {
      const fullMatch = match2[0];
      const linkPath = match2[1] || match2[2];
      if (linkPath.endsWith(".md"))
        continue;
      const file = this.app.metadataCache.getFirstLinkpathDest(linkPath, sourcePath);
      if (file instanceof import_obsidian2.TFile) {
        try {
          new import_obsidian2.Notice(`\u{1F4E4} \uC5C5\uB85C\uB4DC \uC911: ${file.name}`);
          const fileData = await this.app.vault.readBinary(file);
          const uploadResult = await this.api.uploadFile(fileData, file.name);
          if (uploadResult && uploadResult.url) {
            const isImage = fullMatch.startsWith("!");
            const newLink = isImage ? `![${file.name}](${uploadResult.url})` : `[${file.name}](${uploadResult.url})`;
            newContent = newContent.replace(fullMatch, newLink);
          }
        } catch (err) {
          console.error(`Failed to upload ${file.name}:`, err);
        }
      }
    }
    return newContent;
  }
  async pullMemo(uuid) {
    new import_obsidian2.Notice("\u{1F4E1} \uC11C\uBC84\uC5D0\uC11C \uB370\uC774\uD130\uB97C \uAC00\uC838\uC624\uB294 \uC911...");
    try {
      const serverMemo = await this.api.getMemo(uuid);
      await this.saveMemoToVault(serverMemo);
      new import_obsidian2.Notice(`\u2705 \uAC00\uC838\uC624\uAE30 \uC644\uB8CC: ${serverMemo.title}`);
    } catch (e) {
      console.error("Pull Error:", e);
      new import_obsidian2.Notice(`\u274C \uAC00\uC838\uC624\uAE30 \uC2E4\uD328: ${e.message}`);
    }
  }
  async saveMemoToVault(memo) {
    const folderPath = this.settings.syncFolder;
    const adapter = this.app.vault.adapter;
    if (folderPath && !await adapter.exists(folderPath)) {
      await this.app.vault.createFolder(folderPath);
    }
    let content = memo.markdown || memo.content || "";
    content = await this.downloadAttachments(content);
    const safeTitle = (memo.title || memo.uuid || "Untitled").replace(/[\\/:*?"<>|]/g, "_");
    const fileName = `${safeTitle}.md`;
    const path = folderPath ? `${folderPath}/${fileName}` : fileName;
    const existingFile = this.app.vault.getAbstractFileByPath(path);
    if (existingFile instanceof import_obsidian2.TFile) {
      await this.app.vault.modify(existingFile, content);
    } else {
      await this.app.vault.create(path, content);
    }
  }
  async downloadAttachments(content) {
    const serverLinkRegex = /!?\[.*?\]\(\/api\/download\/(.*?)\)/g;
    let newContent = content;
    const matches = Array.from(content.matchAll(serverLinkRegex));
    for (const match of matches) {
      const fullMatch = match[0];
      const fileName = match[1];
      try {
        const url = `${this.settings.serverUrl}/api/download/${fileName}`;
        new import_obsidian2.Notice(`\u{1F4E5} \uB2E4\uC6B4\uB85C\uB4DC \uC911: ${fileName}`);
        const response = await fetch(url, {
          headers: { "Authorization": `Bearer ${this.settings.apiToken}` }
        });
        if (response.ok) {
          const arrayBuffer = await response.arrayBuffer();
          const attachmentPath = this.settings.syncFolder ? `${this.settings.syncFolder}/${fileName}` : fileName;
          if (!await this.app.vault.adapter.exists(attachmentPath)) {
            await this.app.vault.createBinary(attachmentPath, arrayBuffer);
          }
          const isImage = fullMatch.startsWith("!");
          const newLink = isImage ? `![[${fileName}]]` : `[[${fileName}]]`;
          newContent = newContent.replace(fullMatch, newLink);
        }
      } catch (err) {
        console.error(`Failed to download ${fileName}:`, err);
      }
    }
    return newContent;
  }
  async handleProtocol(params) {
    const uuid = params.uuid;
    if (uuid) {
      await this.pullMemo(uuid);
    } else {
      new import_obsidian2.Notice("\u274C \uC720\uD6A8\uD558\uC9C0 \uC54A\uC740 \uBE0C\uB808\uC778\uC0AC\uB8CC \uB9C1\uD06C\uC785\uB2C8\uB2E4.");
    }
  }
};

// main.ts
var DEFAULT_SETTINGS = {
  serverUrl: "http://127.0.0.1:5050",
  apiToken: "",
  syncFolder: "Brainsryo"
};
var BrainsryoPlugin = class extends import_obsidian3.Plugin {
  async onload() {
    await this.loadSettings();
    this.api = new BrainsryoApi(this.settings.serverUrl, this.settings.apiToken);
    this.bridge = new BridgeManager(this.app, this.api, this.settings);
    this.addCommand({
      id: "push-current-note",
      name: "Push Current Note to Brainsryo",
      checkCallback: (checking) => {
        const activeFile = this.app.workspace.getActiveFile();
        if (activeFile) {
          if (!checking) {
            this.bridge.pushNote(activeFile);
          }
          return true;
        }
        return false;
      }
    });
    this.addCommand({
      id: "pull-server-memos",
      name: "Fetch Memo List from Server",
      callback: async () => {
        try {
          const memos = await this.api.listMemos();
          new import_obsidian3.Notice(`\u{1F4E1} \uC11C\uBC84\uC5D0 ${memos.length}\uAC1C\uC758 \uBA54\uBAA8\uAC00 \uC788\uC2B5\uB2C8\uB2E4.`);
        } catch (e) {
          new import_obsidian3.Notice("\u274C \uC11C\uBC84 \uBAA9\uB85D\uC744 \uAC00\uC838\uC624\uC9C0 \uBABB\uD588\uC2B5\uB2C8\uB2E4.");
        }
      }
    });
    this.registerObsidianProtocolHandler("brainsryo-pull", async (params) => {
      await this.bridge.handleProtocol(params);
    });
    this.addRibbonIcon("upload-cloud", "Push Current Note", () => {
      const activeFile = this.app.workspace.getActiveFile();
      if (activeFile) {
        this.bridge.pushNote(activeFile);
      } else {
        new import_obsidian3.Notice("\u274C \uC5F4\uB824\uC788\uB294 \uB178\uD2B8\uAC00 \uC5C6\uC2B5\uB2C8\uB2E4.");
      }
    });
    this.addSettingTab(new BrainsryoSettingTab(this.app, this));
    console.log("\u{1F680} Brainsryo Bridge v3.0.0 Loaded (Manual Mode)");
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }
  async saveSettings() {
    await this.saveData(this.settings);
    this.api = new BrainsryoApi(this.settings.serverUrl, this.settings.apiToken);
  }
};
var BrainsryoSettingTab = class extends import_obsidian3.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.createEl("h2", { text: "Brainsryo Bridge Settings" });
    new import_obsidian3.Setting(containerEl).setName("Server URL").setDesc("\uD648 \uC11C\uBC84 \uC8FC\uC18C\uB97C \uC785\uB825\uD558\uC138\uC694 (\uC608: http://your-server-ip:5050)").addText((text) => text.setPlaceholder("http://localhost:5050").setValue(this.plugin.settings.serverUrl).onChange(async (value) => {
      this.plugin.settings.serverUrl = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian3.Setting(containerEl).setName("API Token").setDesc("\uC11C\uBC84\uC5D0\uC11C \uBC1C\uAE09\uBC1B\uC740 API Key\uB97C \uC785\uB825\uD558\uC138\uC694.").addText((text) => text.setPlaceholder("Enter token").setValue(this.plugin.settings.apiToken).onChange(async (value) => {
      this.plugin.settings.apiToken = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian3.Setting(containerEl).setName("Sync Folder").setDesc("\uBA54\uBAA8\uB97C \uAC00\uC838\uC62C \uD3F4\uB354\uBA85\uC744 \uC785\uB825\uD558\uC138\uC694.").addText((text) => text.setPlaceholder("Brainsryo").setValue(this.plugin.settings.syncFolder).onChange(async (value) => {
      this.plugin.settings.syncFolder = value;
      await this.plugin.saveSettings();
    }));
  }
};
